name: Link Integrity
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress *.pdf *.md 